
python /home/yuhan/neuraltalk/python_features/extract_features.py --caffe ~/caffe/ --model_def /home/yuhan/neuraltalk/python_features/VGG_ILSVRC_16_layers_deploy.prototxt --model ~/caffe/models/vgg_ilsvrc_16/VGG_ILSVRC_16_layers.caffemodel --files /home/yuhan/neuraltalk/python_features/tool/KIDS_PLAYING_BASKETBALL_tasks.txt --out KIDS_PLAYING_BASKETBALL_recog.pickle

python /home/yuhan/neuraltalk/python_features/extract_features.py --caffe ~/caffe/ --model_def /home/yuhan/neuraltalk/python_features/deploy_features.prototxt --model ~/caffe/models/vgg_ilsvrc_16/VGG_ILSVRC_16_layers.caffemodel --files /home/yuhan/neuraltalk/python_features/tool/KIDS_PLAYING_BASKETBALL_tasks.txt --out KIDS_PLAYING_BASKETBALL.pickle
python /home/yuhan/neuraltalk/predict_on_images.py /home/yuhan/neuraltalk/models/flickr8k_cnn_lstm_v1.p -r /home/yuhan/neuraltalk/example_images/frames/KIDS_PLAYING_BASKETBALL -t /home/yuhan/neuraltalk/python_features/tool/KIDS_PLAYING_BASKETBALL_tasks.txt -f KIDS_PLAYING_BASKETBALL.pickle

python /home/yuhan/neuraltalk/python_features/extract_features.py --caffe ~/caffe/ --model_def /home/yuhan/neuraltalk/python_features/deploy_features.prototxt --model ~/caffe/models/vgg_ilsvrc_16/VGG_ILSVRC_16_layers.caffemodel --files /home/yuhan/neuraltalk/python_features/tool/Polar_bears_and_dogs_playing_tasks.txt --out Polar_bears_and_dogs_playing.pickle
python /home/yuhan/neuraltalk/predict_on_images.py /home/yuhan/neuraltalk/models/flickr8k_cnn_lstm_v1.p -r /home/yuhan/neuraltalk/example_images/frames/Polar_bears_and_dogs_playing -t /home/yuhan/neuraltalk/python_features/tool/Polar_bears_and_dogs_playing_tasks.txt -f Polar_bears_and_dogs_playing.pickle

python /home/yuhan/neuraltalk/python_features/extract_features.py --caffe ~/caffe/ --model_def /home/yuhan/neuraltalk/python_features/deploy_features.prototxt --model ~/caffe/models/vgg_ilsvrc_16/VGG_ILSVRC_16_layers.caffemodel --files /home/yuhan/neuraltalk/python_features/tool/GoPro-_Airplane_Waterskiing_tasks.txt --out GoPro-_Airplane_Waterskiing.pickle
python /home/yuhan/neuraltalk/predict_on_images.py /home/yuhan/neuraltalk/models/flickr8k_cnn_lstm_v1.p -r /home/yuhan/neuraltalk/example_images/frames/GoPro-_Airplane_Waterskiing -t /home/yuhan/neuraltalk/python_features/tool/GoPro-_Airplane_Waterskiing_tasks.txt -f GoPro-_Airplane_Waterskiing.pickle

python /home/yuhan/neuraltalk/python_features/extract_features.py --caffe ~/caffe/ --model_def /home/yuhan/neuraltalk/python_features/deploy_features.prototxt --model ~/caffe/models/vgg_ilsvrc_16/VGG_ILSVRC_16_layers.caffemodel --files /home/yuhan/neuraltalk/python_features/tool/12_year_old_Catcher_celebrates_a_strikeout_and_a_win_tasks.txt --out 12_year_old_Catcher_celebrates_a_strikeout_and_a_win.pickle
python /home/yuhan/neuraltalk/predict_on_images.py /home/yuhan/neuraltalk/models/flickr8k_cnn_lstm_v1.p -r /home/yuhan/neuraltalk/example_images/frames/12_year_old_Catcher_celebrates_a_strikeout_and_a_win -t /home/yuhan/neuraltalk/python_features/tool/12_year_old_Catcher_celebrates_a_strikeout_and_a_win_tasks.txt -f 12_year_old_Catcher_celebrates_a_strikeout_and_a_win.pickle

python /home/yuhan/neuraltalk/python_features/extract_features.py --caffe ~/caffe/ --model_def /home/yuhan/neuraltalk/python_features/deploy_features.prototxt --model ~/caffe/models/vgg_ilsvrc_16/VGG_ILSVRC_16_layers.caffemodel --files /home/yuhan/neuraltalk/python_features/tool/Funny_Dogs_Playing_Fetch_In_Sea_At_Goa_Beach_-_Pets_and_Animals_Video_tasks.txt --out Funny_Dogs_Playing_Fetch_In_Sea_At_Goa_Beach_-_Pets_and_Animals_Video.pickle
python /home/yuhan/neuraltalk/predict_on_images.py /home/yuhan/neuraltalk/models/flickr8k_cnn_lstm_v1.p -r /home/yuhan/neuraltalk/example_images/frames/Funny_Dogs_Playing_Fetch_In_Sea_At_Goa_Beach_-_Pets_and_Animals_Video -t /home/yuhan/neuraltalk/python_features/tool/Funny_Dogs_Playing_Fetch_In_Sea_At_Goa_Beach_-_Pets_and_Animals_Video_tasks.txt -f Funny_Dogs_Playing_Fetch_In_Sea_At_Goa_Beach_-_Pets_and_Animals_Video.pickle

python /home/yuhan/neuraltalk/python_features/extract_features.py --caffe ~/caffe/ --model_def /home/yuhan/neuraltalk/python_features/deploy_features.prototxt --model ~/caffe/models/vgg_ilsvrc_16/VGG_ILSVRC_16_layers.caffemodel --files /home/yuhan/neuraltalk/python_features/tool/kids_playing_basketball_tasks.txt --out kids_playing_basketball.pickle
python /home/yuhan/neuraltalk/predict_on_images.py /home/yuhan/neuraltalk/models/flickr8k_cnn_lstm_v1.p -r /home/yuhan/neuraltalk/example_images/frames/kids_playing_basketball -t /home/yuhan/neuraltalk/python_features/tool/kids_playing_basketball_tasks.txt -f kids_playing_basketball.pickle

python /home/yuhan/neuraltalk/python_features/extract_features.py --caffe ~/caffe/ --model_def /home/yuhan/neuraltalk/python_features/deploy_features.prototxt --model ~/caffe/models/vgg_ilsvrc_16/VGG_ILSVRC_16_layers.caffemodel --files /home/yuhan/neuraltalk/python_features/tool/Periscope-_upload_Periscope_video_to_YouTube_tasks.txt --out Periscope-_upload_Periscope_video_to_YouTube.pickle
python /home/yuhan/neuraltalk/predict_on_images.py /home/yuhan/neuraltalk/models/flickr8k_cnn_lstm_v1.p -r /home/yuhan/neuraltalk/example_images/frames/Periscope-_upload_Periscope_video_to_YouTube -t /home/yuhan/neuraltalk/python_features/tool/Periscope-_upload_Periscope_video_to_YouTube_tasks.txt -f Periscope-_upload_Periscope_video_to_YouTube.pickle

python /home/yuhan/neuraltalk/python_features/extract_features.py --caffe ~/caffe/ --model_def /home/yuhan/neuraltalk/python_features/deploy_features.prototxt --model ~/caffe/models/vgg_ilsvrc_16/VGG_ILSVRC_16_layers.caffemodel --files /home/yuhan/neuraltalk/python_features/tool/Cat_and_Dog_Play_Fighting_tasks.txt --out Cat_and_Dog_Play_Fighting.pickle
python /home/yuhan/neuraltalk/predict_on_images.py /home/yuhan/neuraltalk/models/flickr8k_cnn_lstm_v1.p -r /home/yuhan/neuraltalk/example_images/frames/Cat_and_Dog_Play_Fighting -t /home/yuhan/neuraltalk/python_features/tool/Cat_and_Dog_Play_Fighting_tasks.txt -f Cat_and_Dog_Play_Fighting.pickle

python /home/yuhan/neuraltalk/python_features/extract_features.py --caffe ~/caffe/ --model_def /home/yuhan/neuraltalk/python_features/deploy_features.prototxt --model ~/caffe/models/vgg_ilsvrc_16/VGG_ILSVRC_16_layers.caffemodel --files /home/yuhan/neuraltalk/python_features/tool/Newborn_Goat_tries_to_cross_over_Dog_tasks.txt --out Newborn_Goat_tries_to_cross_over_Dog.pickle
python /home/yuhan/neuraltalk/predict_on_images.py /home/yuhan/neuraltalk/models/flickr8k_cnn_lstm_v1.p -r /home/yuhan/neuraltalk/example_images/frames/Newborn_Goat_tries_to_cross_over_Dog -t /home/yuhan/neuraltalk/python_features/tool/Newborn_Goat_tries_to_cross_over_Dog_tasks.txt -f Newborn_Goat_tries_to_cross_over_Dog.pickle

python /home/yuhan/neuraltalk/python_features/extract_features.py --caffe ~/caffe/ --model_def /home/yuhan/neuraltalk/python_features/deploy_features.prototxt --model ~/caffe/models/vgg_ilsvrc_16/VGG_ILSVRC_16_layers.caffemodel --files /home/yuhan/neuraltalk/python_features/tool/street_guitar_tasks.txt --out street_guitar.pickle
python /home/yuhan/neuraltalk/predict_on_images.py /home/yuhan/neuraltalk/models/flickr8k_cnn_lstm_v1.p -r /home/yuhan/neuraltalk/example_images/frames/street_guitar -t /home/yuhan/neuraltalk/python_features/tool/street_guitar_tasks.txt -f street_guitar.pickle

