python subsample.py /home/t-yuche/deep-video/data/frames/amazing_lion_vs_zebra__lion_kills_zebra_almost__lion_hunting_zebra__zebra_escapes_lion_kill_kXwG-ms63X8
python subsample.py /home/t-yuche/deep-video/data/frames/gopro_first_encounter_with_a_wild_zebra_NRkaTGKZFL8
python subsample.py /home/t-yuche/deep-video/data/frames/warty_pigs_through_google_glass_Xs3x3lCl8_E
python subsample.py /home/t-yuche/deep-video/data/frames/playing_with_the_squirrels_in_st_pauls_church_yard_through_google_glass_aDkGhiBfuY0
python subsample.py /home/t-yuche/deep-video/data/frames/new_home_reserve_tux_couch_loveseat_ottoman_building_CST9RF4_JwA
python subsample.py /home/t-yuche/deep-video/data/frames/horseback_riding_at_meramec_farm_mo_recorded_with_google_glass_Z7cYAXJ5STE
python subsample.py /home/t-yuche/deep-video/data/frames/sf_ride_with_google_glass_ZmzW6UyOw9A
python subsample.py /home/t-yuche/deep-video/data/frames/Polar_bears_and_dogs_playing
python subsample.py /home/t-yuche/deep-video/data/frames/two_dogs_dining_EVwlMVYqMu4
python subsample.py /home/t-yuche/deep-video/data/frames/playing_tennis_with_google_glass_r8GS60CmVRg
python subsample.py /home/t-yuche/deep-video/data/frames/grandpa_goes_out_to_dinner_ig17lgCtoFg
python subsample.py /home/t-yuche/deep-video/data/frames/snowboarding_with_a_gopro_hero3_black_UGY82g3gTSc
python subsample.py /home/t-yuche/deep-video/data/frames/thoroughbred_horse_through_googleglass_IbXdHo9CN1I
python subsample.py /home/t-yuche/deep-video/data/frames/yongpyong_resort_south_korea_snowboarding_with_google_glass__part_3_1LzvqaAu_Mk
python subsample.py /home/t-yuche/deep-video/data/frames/recorded_through_google_glass_a_very_happy_dog_VrYKLmQ-FYI
python subsample.py /home/t-yuche/deep-video/data/frames/GoPro-_Airplane_Waterskiing
python subsample.py /home/t-yuche/deep-video/data/frames/my_favorite_living_room_home_decor_bobkona_trenton_sectional_sofa__32b37fusIY
python subsample.py /home/t-yuche/deep-video/data/frames/football_soccer_through_google_glass_60LguMbHG2k
python subsample.py /home/t-yuche/deep-video/data/frames/silly_kitty_on_the_red_bed_wuBsis_Xvx4
python subsample.py /home/t-yuche/deep-video/data/frames/mcdonalds_random_red_couch_commercial_0kEJf3zKlWQ
python subsample.py /home/t-yuche/deep-video/data/frames/Cat_and_Dog_Play_Fighting
python subsample.py /home/t-yuche/deep-video/data/frames/gerenuk_through_google_glass_XvWdwea5PKs
python subsample.py /home/t-yuche/deep-video/data/frames/kids_playing_basketball
python subsample.py /home/t-yuche/deep-video/data/frames/bike_riding_kid_hit_by_car__caught_on_dash_cam_zhsQd8TE4Ag
python subsample.py /home/t-yuche/deep-video/data/frames/emma_and_cinnamon__little_girl_and_horse_are_best_friends_LZmIkHvGEfs
python subsample.py /home/t-yuche/deep-video/data/frames/beyonce__drunk_in_love__red_couch_session_by_dan_henig_a1puW6igXcg
python subsample.py /home/t-yuche/deep-video/data/frames/google_glass_lunch_with_restaurant_reporter_kevin_pang_DHkjf-znowA
python subsample.py /home/t-yuche/deep-video/data/frames/christmas_break_gopro_CB662uFL8tY
python subsample.py /home/t-yuche/deep-video/data/frames/meet_kumari_the_porcupine_ID5irdY08xA
python subsample.py /home/t-yuche/deep-video/data/frames/red_suede_couch_prod_luke_ballistic_official_music_video__blake_graham_x_macale_media_CSbtEuoLj88
python subsample.py /home/t-yuche/deep-video/data/frames/12_year_old_Catcher_celebrates_a_strikeout_and_a_win
python subsample.py /home/t-yuche/deep-video/data/frames/google_glass_films_google_glass__real_estate_tour_throughglass_7e5iDdPGeGA
python subsample.py /home/t-yuche/deep-video/data/frames/google_glass_elephants_EaShz4jRL_s
python subsample.py /home/t-yuche/deep-video/data/frames/gopro_bali_christmas_holidays_20142015_zRw4EyYcvmA
python subsample.py /home/t-yuche/deep-video/data/frames/Sultans_Of_Swing_-_Dire_Straits_Cover_Guitar_HD_Ao_vivo_São_Paulo_2014_(Willian_Lee)
python subsample.py /home/t-yuche/deep-video/data/frames/tcgs__sandwich_night_2013_through_google_glass_3njPQW34BFQ
python subsample.py /home/t-yuche/deep-video/data/frames/Funny_Dogs_Playing_Fetch_In_Sea_At_Goa_Beach_-_Pets_and_Animals_Video
python subsample.py /home/t-yuche/deep-video/data/frames/google_glass_on_planet_of_horses_L7wysTG37kk
python subsample.py /home/t-yuche/deep-video/data/frames/Periscope-_upload_Periscope_video_to_YouTube
python subsample.py /home/t-yuche/deep-video/data/frames/Hercules_playing_on_the_beach
python subsample.py /home/t-yuche/deep-video/data/frames/skating_with_google_glass_by_night_qK5gkJOvIvw
python subsample.py /home/t-yuche/deep-video/data/frames/uts_boxing_for_mma_class_gopro_hero_3_HVtVpkkYGn0
python subsample.py /home/t-yuche/deep-video/data/frames/homespace_red_sofaliving_room_inspiration_VDbvAxmM1VM
python subsample.py /home/t-yuche/deep-video/data/frames/KIDS_PLAYING_BASKETBALL_2
python subsample.py /home/t-yuche/deep-video/data/frames/red_couch_interviews_2015_totalsports_xterra_grabouw_U0u-NCw78ik
python subsample.py /home/t-yuche/deep-video/data/frames/zebra_outside_the_tent_n6C0gU2kS9Y
python subsample.py /home/t-yuche/deep-video/data/frames/Newborn_Goat_tries_to_cross_over_Dog
python subsample.py /home/t-yuche/deep-video/data/frames/christmas_announcement_another_one_in_the_oven__google_glass_zfABTFNWcYU
