# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: model.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='model.proto',
  package='csail.yuhan.panorama',
  serialized_pb='\n\x0bmodel.proto\x12\x14\x63sail.yuhan.panorama\"\xb7\x02\n\x0eModelParameter\x12\x0c\n\x04name\x18\x01 \x01(\t\x12/\n\x04type\x18\x02 \x02(\x0e\x32!.csail.yuhan.panorama.RequestType\x12\x0f\n\x07\x63ompute\x18\x03 \x01(\t\x12\x0e\n\x06memory\x18\x04 \x01(\t\x12\x17\n\x0floading_latency\x18\x05 \x01(\x02\x12\x10\n\x08\x61\x63\x63uracy\x18\x06 \x01(\x02\x12\x17\n\x0f\x63ompute_latency\x18\x07 \x01(\x02\x12\x1b\n\x13\x63pu_compute_latency\x18\x08 \x01(\x02\x12\x16\n\x0e\x63ompute_energy\x18\t \x01(\x02\x12\x19\n\x11s_compute_latency\x18\n \x01(\x02\x12\x19\n\x11s_loading_latency\x18\x0b \x01(\x02\x12\x16\n\x0eloading_energy\x18\x0c \x01(\x02\"V\n\x10\x41pplicationModel\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x34\n\x06models\x18\x02 \x03(\x0b\x32$.csail.yuhan.panorama.ModelParameter*#\n\x0bRequestType\x12\x08\n\x04\x46\x41\x43\x45\x10\x01\x12\n\n\x06OBJECT\x10\x02')

_REQUESTTYPE = _descriptor.EnumDescriptor(
  name='RequestType',
  full_name='csail.yuhan.panorama.RequestType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='FACE', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OBJECT', index=1, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=439,
  serialized_end=474,
)

RequestType = enum_type_wrapper.EnumTypeWrapper(_REQUESTTYPE)
FACE = 1
OBJECT = 2



_MODELPARAMETER = _descriptor.Descriptor(
  name='ModelParameter',
  full_name='csail.yuhan.panorama.ModelParameter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='csail.yuhan.panorama.ModelParameter.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='csail.yuhan.panorama.ModelParameter.type', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='compute', full_name='csail.yuhan.panorama.ModelParameter.compute', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='memory', full_name='csail.yuhan.panorama.ModelParameter.memory', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='loading_latency', full_name='csail.yuhan.panorama.ModelParameter.loading_latency', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='accuracy', full_name='csail.yuhan.panorama.ModelParameter.accuracy', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='compute_latency', full_name='csail.yuhan.panorama.ModelParameter.compute_latency', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cpu_compute_latency', full_name='csail.yuhan.panorama.ModelParameter.cpu_compute_latency', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='compute_energy', full_name='csail.yuhan.panorama.ModelParameter.compute_energy', index=8,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='s_compute_latency', full_name='csail.yuhan.panorama.ModelParameter.s_compute_latency', index=9,
      number=10, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='s_loading_latency', full_name='csail.yuhan.panorama.ModelParameter.s_loading_latency', index=10,
      number=11, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='loading_energy', full_name='csail.yuhan.panorama.ModelParameter.loading_energy', index=11,
      number=12, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=38,
  serialized_end=349,
)


_APPLICATIONMODEL = _descriptor.Descriptor(
  name='ApplicationModel',
  full_name='csail.yuhan.panorama.ApplicationModel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='csail.yuhan.panorama.ApplicationModel.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='models', full_name='csail.yuhan.panorama.ApplicationModel.models', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=351,
  serialized_end=437,
)

_MODELPARAMETER.fields_by_name['type'].enum_type = _REQUESTTYPE
_APPLICATIONMODEL.fields_by_name['models'].message_type = _MODELPARAMETER
DESCRIPTOR.message_types_by_name['ModelParameter'] = _MODELPARAMETER
DESCRIPTOR.message_types_by_name['ApplicationModel'] = _APPLICATIONMODEL

class ModelParameter(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MODELPARAMETER

  # @@protoc_insertion_point(class_scope:csail.yuhan.panorama.ModelParameter)

class ApplicationModel(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _APPLICATIONMODEL

  # @@protoc_insertion_point(class_scope:csail.yuhan.panorama.ApplicationModel)


# @@protoc_insertion_point(module_scope)
