
python /home/t-yuche/neuraltalk/python_features/extract_features.py  --gpu --caffe ~/caffe/ --model_def /home/t-yuche/neuraltalk/python_features/deploy_features.prototxt --model /home/t-yuche/caffe/models/vgg_ilsvrc_16/VGG_ILSVRC_16_layers.caffemodel --files /home/t-yuche/neuraltalk/python_features/tool/tmp/horseback_riding_at_meramec_farm_mo_recorded_with_google_glass_Z7cYAXJ5STE_tasks.txt --out /home/t-yuche/neuraltalk/python_features/caption/horseback_riding_at_meramec_farm_mo_recorded_with_google_glass_Z7cYAXJ5STE.pickle
python /home/t-yuche/neuraltalk/predict_on_images.py /home/t-yuche/neuraltalk/models/flickr8k_cnn_lstm_v1.p -r /home/t-yuche/deep-video/data/frames/horseback_riding_at_meramec_farm_mo_recorded_with_google_glass_Z7cYAXJ5STE -t /home/t-yuche/neuraltalk/python_features/tool/tmp/horseback_riding_at_meramec_farm_mo_recorded_with_google_glass_Z7cYAXJ5STE_tasks.txt -f  /home/t-yuche/neuraltalk/python_features/caption/horseback_riding_at_meramec_farm_mo_recorded_with_google_glass_Z7cYAXJ5STE.pickle -of  /home/t-yuche/neuraltalk/python_features/caption/horseback_riding_at_meramec_farm_mo_recorded_with_google_glass_Z7cYAXJ5STE_5_caption.json &

python /home/t-yuche/neuraltalk/python_features/extract_features.py  --gpu --caffe ~/caffe/ --model_def /home/t-yuche/neuraltalk/python_features/deploy_features.prototxt --model /home/t-yuche/caffe/models/vgg_ilsvrc_16/VGG_ILSVRC_16_layers.caffemodel --files /home/t-yuche/neuraltalk/python_features/tool/tmp/sf_ride_with_google_glass_ZmzW6UyOw9A_tasks.txt --out /home/t-yuche/neuraltalk/python_features/caption/sf_ride_with_google_glass_ZmzW6UyOw9A.pickle
python /home/t-yuche/neuraltalk/predict_on_images.py /home/t-yuche/neuraltalk/models/flickr8k_cnn_lstm_v1.p -r /home/t-yuche/deep-video/data/frames/sf_ride_with_google_glass_ZmzW6UyOw9A -t /home/t-yuche/neuraltalk/python_features/tool/tmp/sf_ride_with_google_glass_ZmzW6UyOw9A_tasks.txt -f  /home/t-yuche/neuraltalk/python_features/caption/sf_ride_with_google_glass_ZmzW6UyOw9A.pickle -of  /home/t-yuche/neuraltalk/python_features/caption/sf_ride_with_google_glass_ZmzW6UyOw9A_5_caption.json &


python /home/t-yuche/neuraltalk/python_features/extract_features.py  --gpu --caffe ~/caffe/ --model_def /home/t-yuche/neuraltalk/python_features/deploy_features.prototxt --model /home/t-yuche/caffe/models/vgg_ilsvrc_16/VGG_ILSVRC_16_layers.caffemodel --files /home/t-yuche/neuraltalk/python_features/tool/tmp/two_dogs_dining_EVwlMVYqMu4_tasks.txt --out /home/t-yuche/neuraltalk/python_features/caption/two_dogs_dining_EVwlMVYqMu4.pickle
python /home/t-yuche/neuraltalk/predict_on_images.py /home/t-yuche/neuraltalk/models/flickr8k_cnn_lstm_v1.p -r /home/t-yuche/deep-video/data/frames/two_dogs_dining_EVwlMVYqMu4 -t /home/t-yuche/neuraltalk/python_features/tool/tmp/two_dogs_dining_EVwlMVYqMu4_tasks.txt -f  /home/t-yuche/neuraltalk/python_features/caption/two_dogs_dining_EVwlMVYqMu4.pickle -of  /home/t-yuche/neuraltalk/python_features/caption/two_dogs_dining_EVwlMVYqMu4_5_caption.json &

python /home/t-yuche/neuraltalk/python_features/extract_features.py  --gpu --caffe ~/caffe/ --model_def /home/t-yuche/neuraltalk/python_features/deploy_features.prototxt --model /home/t-yuche/caffe/models/vgg_ilsvrc_16/VGG_ILSVRC_16_layers.caffemodel --files /home/t-yuche/neuraltalk/python_features/tool/tmp/playing_tennis_with_google_glass_r8GS60CmVRg_tasks.txt --out /home/t-yuche/neuraltalk/python_features/caption/playing_tennis_with_google_glass_r8GS60CmVRg.pickle
python /home/t-yuche/neuraltalk/predict_on_images.py /home/t-yuche/neuraltalk/models/flickr8k_cnn_lstm_v1.p -r /home/t-yuche/deep-video/data/frames/playing_tennis_with_google_glass_r8GS60CmVRg -t /home/t-yuche/neuraltalk/python_features/tool/tmp/playing_tennis_with_google_glass_r8GS60CmVRg_tasks.txt -f  /home/t-yuche/neuraltalk/python_features/caption/playing_tennis_with_google_glass_r8GS60CmVRg.pickle -of  /home/t-yuche/neuraltalk/python_features/caption/playing_tennis_with_google_glass_r8GS60CmVRg_5_caption.json &

python /home/t-yuche/neuraltalk/python_features/extract_features.py  --gpu --caffe ~/caffe/ --model_def /home/t-yuche/neuraltalk/python_features/deploy_features.prototxt --model /home/t-yuche/caffe/models/vgg_ilsvrc_16/VGG_ILSVRC_16_layers.caffemodel --files /home/t-yuche/neuraltalk/python_features/tool/tmp/grandpa_goes_out_to_dinner_ig17lgCtoFg_tasks.txt --out /home/t-yuche/neuraltalk/python_features/caption/grandpa_goes_out_to_dinner_ig17lgCtoFg.pickle
python /home/t-yuche/neuraltalk/predict_on_images.py /home/t-yuche/neuraltalk/models/flickr8k_cnn_lstm_v1.p -r /home/t-yuche/deep-video/data/frames/grandpa_goes_out_to_dinner_ig17lgCtoFg -t /home/t-yuche/neuraltalk/python_features/tool/tmp/grandpa_goes_out_to_dinner_ig17lgCtoFg_tasks.txt -f  /home/t-yuche/neuraltalk/python_features/caption/grandpa_goes_out_to_dinner_ig17lgCtoFg.pickle -of  /home/t-yuche/neuraltalk/python_features/caption/grandpa_goes_out_to_dinner_ig17lgCtoFg_5_caption.json &

python /home/t-yuche/neuraltalk/python_features/extract_features.py  --gpu --caffe ~/caffe/ --model_def /home/t-yuche/neuraltalk/python_features/deploy_features.prototxt --model /home/t-yuche/caffe/models/vgg_ilsvrc_16/VGG_ILSVRC_16_layers.caffemodel --files /home/t-yuche/neuraltalk/python_features/tool/tmp/snowboarding_with_a_gopro_hero3_black_UGY82g3gTSc_tasks.txt --out /home/t-yuche/neuraltalk/python_features/caption/snowboarding_with_a_gopro_hero3_black_UGY82g3gTSc.pickle
python /home/t-yuche/neuraltalk/predict_on_images.py /home/t-yuche/neuraltalk/models/flickr8k_cnn_lstm_v1.p -r /home/t-yuche/deep-video/data/frames/snowboarding_with_a_gopro_hero3_black_UGY82g3gTSc -t /home/t-yuche/neuraltalk/python_features/tool/tmp/snowboarding_with_a_gopro_hero3_black_UGY82g3gTSc_tasks.txt -f  /home/t-yuche/neuraltalk/python_features/caption/snowboarding_with_a_gopro_hero3_black_UGY82g3gTSc.pickle -of  /home/t-yuche/neuraltalk/python_features/caption/snowboarding_with_a_gopro_hero3_black_UGY82g3gTSc_5_caption.json &

python /home/t-yuche/neuraltalk/python_features/extract_features.py  --gpu --caffe ~/caffe/ --model_def /home/t-yuche/neuraltalk/python_features/deploy_features.prototxt --model /home/t-yuche/caffe/models/vgg_ilsvrc_16/VGG_ILSVRC_16_layers.caffemodel --files /home/t-yuche/neuraltalk/python_features/tool/tmp/thoroughbred_horse_through_googleglass_IbXdHo9CN1I_tasks.txt --out /home/t-yuche/neuraltalk/python_features/caption/thoroughbred_horse_through_googleglass_IbXdHo9CN1I.pickle
python /home/t-yuche/neuraltalk/predict_on_images.py /home/t-yuche/neuraltalk/models/flickr8k_cnn_lstm_v1.p -r /home/t-yuche/deep-video/data/frames/thoroughbred_horse_through_googleglass_IbXdHo9CN1I -t /home/t-yuche/neuraltalk/python_features/tool/tmp/thoroughbred_horse_through_googleglass_IbXdHo9CN1I_tasks.txt -f  /home/t-yuche/neuraltalk/python_features/caption/thoroughbred_horse_through_googleglass_IbXdHo9CN1I.pickle -of  /home/t-yuche/neuraltalk/python_features/caption/thoroughbred_horse_through_googleglass_IbXdHo9CN1I_5_caption.json &

python /home/t-yuche/neuraltalk/python_features/extract_features.py  --gpu --caffe ~/caffe/ --model_def /home/t-yuche/neuraltalk/python_features/deploy_features.prototxt --model /home/t-yuche/caffe/models/vgg_ilsvrc_16/VGG_ILSVRC_16_layers.caffemodel --files /home/t-yuche/neuraltalk/python_features/tool/tmp/yongpyong_resort_south_korea_snowboarding_with_google_glass__part_3_1LzvqaAu_Mk_tasks.txt --out /home/t-yuche/neuraltalk/python_features/caption/yongpyong_resort_south_korea_snowboarding_with_google_glass__part_3_1LzvqaAu_Mk.pickle
python /home/t-yuche/neuraltalk/predict_on_images.py /home/t-yuche/neuraltalk/models/flickr8k_cnn_lstm_v1.p -r /home/t-yuche/deep-video/data/frames/yongpyong_resort_south_korea_snowboarding_with_google_glass__part_3_1LzvqaAu_Mk -t /home/t-yuche/neuraltalk/python_features/tool/tmp/yongpyong_resort_south_korea_snowboarding_with_google_glass__part_3_1LzvqaAu_Mk_tasks.txt -f  /home/t-yuche/neuraltalk/python_features/caption/yongpyong_resort_south_korea_snowboarding_with_google_glass__part_3_1LzvqaAu_Mk.pickle -of  /home/t-yuche/neuraltalk/python_features/caption/yongpyong_resort_south_korea_snowboarding_with_google_glass__part_3_1LzvqaAu_Mk_5_caption.json &

python /home/t-yuche/neuraltalk/python_features/extract_features.py  --gpu --caffe ~/caffe/ --model_def /home/t-yuche/neuraltalk/python_features/deploy_features.prototxt --model /home/t-yuche/caffe/models/vgg_ilsvrc_16/VGG_ILSVRC_16_layers.caffemodel --files /home/t-yuche/neuraltalk/python_features/tool/tmp/recorded_through_google_glass_a_very_happy_dog_VrYKLmQ-FYI_tasks.txt --out /home/t-yuche/neuraltalk/python_features/caption/recorded_through_google_glass_a_very_happy_dog_VrYKLmQ-FYI.pickle
python /home/t-yuche/neuraltalk/predict_on_images.py /home/t-yuche/neuraltalk/models/flickr8k_cnn_lstm_v1.p -r /home/t-yuche/deep-video/data/frames/recorded_through_google_glass_a_very_happy_dog_VrYKLmQ-FYI -t /home/t-yuche/neuraltalk/python_features/tool/tmp/recorded_through_google_glass_a_very_happy_dog_VrYKLmQ-FYI_tasks.txt -f  /home/t-yuche/neuraltalk/python_features/caption/recorded_through_google_glass_a_very_happy_dog_VrYKLmQ-FYI.pickle -of  /home/t-yuche/neuraltalk/python_features/caption/recorded_through_google_glass_a_very_happy_dog_VrYKLmQ-FYI_5_caption.json &


python /home/t-yuche/neuraltalk/python_features/extract_features.py  --gpu --caffe ~/caffe/ --model_def /home/t-yuche/neuraltalk/python_features/deploy_features.prototxt --model /home/t-yuche/caffe/models/vgg_ilsvrc_16/VGG_ILSVRC_16_layers.caffemodel --files /home/t-yuche/neuraltalk/python_features/tool/tmp/my_favorite_living_room_home_decor_bobkona_trenton_sectional_sofa__32b37fusIY_tasks.txt --out /home/t-yuche/neuraltalk/python_features/caption/my_favorite_living_room_home_decor_bobkona_trenton_sectional_sofa__32b37fusIY.pickle
python /home/t-yuche/neuraltalk/predict_on_images.py /home/t-yuche/neuraltalk/models/flickr8k_cnn_lstm_v1.p -r /home/t-yuche/deep-video/data/frames/my_favorite_living_room_home_decor_bobkona_trenton_sectional_sofa__32b37fusIY -t /home/t-yuche/neuraltalk/python_features/tool/tmp/my_favorite_living_room_home_decor_bobkona_trenton_sectional_sofa__32b37fusIY_tasks.txt -f  /home/t-yuche/neuraltalk/python_features/caption/my_favorite_living_room_home_decor_bobkona_trenton_sectional_sofa__32b37fusIY.pickle -of  /home/t-yuche/neuraltalk/python_features/caption/my_favorite_living_room_home_decor_bobkona_trenton_sectional_sofa__32b37fusIY_5_caption.json &

python /home/t-yuche/neuraltalk/python_features/extract_features.py  --gpu --caffe ~/caffe/ --model_def /home/t-yuche/neuraltalk/python_features/deploy_features.prototxt --model /home/t-yuche/caffe/models/vgg_ilsvrc_16/VGG_ILSVRC_16_layers.caffemodel --files /home/t-yuche/neuraltalk/python_features/tool/tmp/football_soccer_through_google_glass_60LguMbHG2k_tasks.txt --out /home/t-yuche/neuraltalk/python_features/caption/football_soccer_through_google_glass_60LguMbHG2k.pickle
python /home/t-yuche/neuraltalk/predict_on_images.py /home/t-yuche/neuraltalk/models/flickr8k_cnn_lstm_v1.p -r /home/t-yuche/deep-video/data/frames/football_soccer_through_google_glass_60LguMbHG2k -t /home/t-yuche/neuraltalk/python_features/tool/tmp/football_soccer_through_google_glass_60LguMbHG2k_tasks.txt -f  /home/t-yuche/neuraltalk/python_features/caption/football_soccer_through_google_glass_60LguMbHG2k.pickle -of  /home/t-yuche/neuraltalk/python_features/caption/football_soccer_through_google_glass_60LguMbHG2k_5_caption.json &

python /home/t-yuche/neuraltalk/python_features/extract_features.py  --gpu --caffe ~/caffe/ --model_def /home/t-yuche/neuraltalk/python_features/deploy_features.prototxt --model /home/t-yuche/caffe/models/vgg_ilsvrc_16/VGG_ILSVRC_16_layers.caffemodel --files /home/t-yuche/neuraltalk/python_features/tool/tmp/silly_kitty_on_the_red_bed_wuBsis_Xvx4_tasks.txt --out /home/t-yuche/neuraltalk/python_features/caption/silly_kitty_on_the_red_bed_wuBsis_Xvx4.pickle
python /home/t-yuche/neuraltalk/predict_on_images.py /home/t-yuche/neuraltalk/models/flickr8k_cnn_lstm_v1.p -r /home/t-yuche/deep-video/data/frames/silly_kitty_on_the_red_bed_wuBsis_Xvx4 -t /home/t-yuche/neuraltalk/python_features/tool/tmp/silly_kitty_on_the_red_bed_wuBsis_Xvx4_tasks.txt -f  /home/t-yuche/neuraltalk/python_features/caption/silly_kitty_on_the_red_bed_wuBsis_Xvx4.pickle -of  /home/t-yuche/neuraltalk/python_features/caption/silly_kitty_on_the_red_bed_wuBsis_Xvx4_5_caption.json &

python /home/t-yuche/neuraltalk/python_features/extract_features.py  --gpu --caffe ~/caffe/ --model_def /home/t-yuche/neuraltalk/python_features/deploy_features.prototxt --model /home/t-yuche/caffe/models/vgg_ilsvrc_16/VGG_ILSVRC_16_layers.caffemodel --files /home/t-yuche/neuraltalk/python_features/tool/tmp/mcdonalds_random_red_couch_commercial_0kEJf3zKlWQ_tasks.txt --out /home/t-yuche/neuraltalk/python_features/caption/mcdonalds_random_red_couch_commercial_0kEJf3zKlWQ.pickle
python /home/t-yuche/neuraltalk/predict_on_images.py /home/t-yuche/neuraltalk/models/flickr8k_cnn_lstm_v1.p -r /home/t-yuche/deep-video/data/frames/mcdonalds_random_red_couch_commercial_0kEJf3zKlWQ -t /home/t-yuche/neuraltalk/python_features/tool/tmp/mcdonalds_random_red_couch_commercial_0kEJf3zKlWQ_tasks.txt -f  /home/t-yuche/neuraltalk/python_features/caption/mcdonalds_random_red_couch_commercial_0kEJf3zKlWQ.pickle -of  /home/t-yuche/neuraltalk/python_features/caption/mcdonalds_random_red_couch_commercial_0kEJf3zKlWQ_5_caption.json &


python /home/t-yuche/neuraltalk/python_features/extract_features.py  --gpu --caffe ~/caffe/ --model_def /home/t-yuche/neuraltalk/python_features/deploy_features.prototxt --model /home/t-yuche/caffe/models/vgg_ilsvrc_16/VGG_ILSVRC_16_layers.caffemodel --files /home/t-yuche/neuraltalk/python_features/tool/tmp/gerenuk_through_google_glass_XvWdwea5PKs_tasks.txt --out /home/t-yuche/neuraltalk/python_features/caption/gerenuk_through_google_glass_XvWdwea5PKs.pickle
python /home/t-yuche/neuraltalk/predict_on_images.py /home/t-yuche/neuraltalk/models/flickr8k_cnn_lstm_v1.p -r /home/t-yuche/deep-video/data/frames/gerenuk_through_google_glass_XvWdwea5PKs -t /home/t-yuche/neuraltalk/python_features/tool/tmp/gerenuk_through_google_glass_XvWdwea5PKs_tasks.txt -f  /home/t-yuche/neuraltalk/python_features/caption/gerenuk_through_google_glass_XvWdwea5PKs.pickle -of  /home/t-yuche/neuraltalk/python_features/caption/gerenuk_through_google_glass_XvWdwea5PKs_5_caption.json &


python /home/t-yuche/neuraltalk/python_features/extract_features.py  --gpu --caffe ~/caffe/ --model_def /home/t-yuche/neuraltalk/python_features/deploy_features.prototxt --model /home/t-yuche/caffe/models/vgg_ilsvrc_16/VGG_ILSVRC_16_layers.caffemodel --files /home/t-yuche/neuraltalk/python_features/tool/tmp/bike_riding_kid_hit_by_car__caught_on_dash_cam_zhsQd8TE4Ag_tasks.txt --out /home/t-yuche/neuraltalk/python_features/caption/bike_riding_kid_hit_by_car__caught_on_dash_cam_zhsQd8TE4Ag.pickle
python /home/t-yuche/neuraltalk/predict_on_images.py /home/t-yuche/neuraltalk/models/flickr8k_cnn_lstm_v1.p -r /home/t-yuche/deep-video/data/frames/bike_riding_kid_hit_by_car__caught_on_dash_cam_zhsQd8TE4Ag -t /home/t-yuche/neuraltalk/python_features/tool/tmp/bike_riding_kid_hit_by_car__caught_on_dash_cam_zhsQd8TE4Ag_tasks.txt -f  /home/t-yuche/neuraltalk/python_features/caption/bike_riding_kid_hit_by_car__caught_on_dash_cam_zhsQd8TE4Ag.pickle -of  /home/t-yuche/neuraltalk/python_features/caption/bike_riding_kid_hit_by_car__caught_on_dash_cam_zhsQd8TE4Ag_5_caption.json &

python /home/t-yuche/neuraltalk/python_features/extract_features.py  --gpu --caffe ~/caffe/ --model_def /home/t-yuche/neuraltalk/python_features/deploy_features.prototxt --model /home/t-yuche/caffe/models/vgg_ilsvrc_16/VGG_ILSVRC_16_layers.caffemodel --files /home/t-yuche/neuraltalk/python_features/tool/tmp/emma_and_cinnamon__little_girl_and_horse_are_best_friends_LZmIkHvGEfs_tasks.txt --out /home/t-yuche/neuraltalk/python_features/caption/emma_and_cinnamon__little_girl_and_horse_are_best_friends_LZmIkHvGEfs.pickle
python /home/t-yuche/neuraltalk/predict_on_images.py /home/t-yuche/neuraltalk/models/flickr8k_cnn_lstm_v1.p -r /home/t-yuche/deep-video/data/frames/emma_and_cinnamon__little_girl_and_horse_are_best_friends_LZmIkHvGEfs -t /home/t-yuche/neuraltalk/python_features/tool/tmp/emma_and_cinnamon__little_girl_and_horse_are_best_friends_LZmIkHvGEfs_tasks.txt -f  /home/t-yuche/neuraltalk/python_features/caption/emma_and_cinnamon__little_girl_and_horse_are_best_friends_LZmIkHvGEfs.pickle -of  /home/t-yuche/neuraltalk/python_features/caption/emma_and_cinnamon__little_girl_and_horse_are_best_friends_LZmIkHvGEfs_5_caption.json &

python /home/t-yuche/neuraltalk/python_features/extract_features.py  --gpu --caffe ~/caffe/ --model_def /home/t-yuche/neuraltalk/python_features/deploy_features.prototxt --model /home/t-yuche/caffe/models/vgg_ilsvrc_16/VGG_ILSVRC_16_layers.caffemodel --files /home/t-yuche/neuraltalk/python_features/tool/tmp/beyonce__drunk_in_love__red_couch_session_by_dan_henig_a1puW6igXcg_tasks.txt --out /home/t-yuche/neuraltalk/python_features/caption/beyonce__drunk_in_love__red_couch_session_by_dan_henig_a1puW6igXcg.pickle
python /home/t-yuche/neuraltalk/predict_on_images.py /home/t-yuche/neuraltalk/models/flickr8k_cnn_lstm_v1.p -r /home/t-yuche/deep-video/data/frames/beyonce__drunk_in_love__red_couch_session_by_dan_henig_a1puW6igXcg -t /home/t-yuche/neuraltalk/python_features/tool/tmp/beyonce__drunk_in_love__red_couch_session_by_dan_henig_a1puW6igXcg_tasks.txt -f  /home/t-yuche/neuraltalk/python_features/caption/beyonce__drunk_in_love__red_couch_session_by_dan_henig_a1puW6igXcg.pickle -of  /home/t-yuche/neuraltalk/python_features/caption/beyonce__drunk_in_love__red_couch_session_by_dan_henig_a1puW6igXcg_5_caption.json &

python /home/t-yuche/neuraltalk/python_features/extract_features.py  --gpu --caffe ~/caffe/ --model_def /home/t-yuche/neuraltalk/python_features/deploy_features.prototxt --model /home/t-yuche/caffe/models/vgg_ilsvrc_16/VGG_ILSVRC_16_layers.caffemodel --files /home/t-yuche/neuraltalk/python_features/tool/tmp/google_glass_lunch_with_restaurant_reporter_kevin_pang_DHkjf-znowA_tasks.txt --out /home/t-yuche/neuraltalk/python_features/caption/google_glass_lunch_with_restaurant_reporter_kevin_pang_DHkjf-znowA.pickle
python /home/t-yuche/neuraltalk/predict_on_images.py /home/t-yuche/neuraltalk/models/flickr8k_cnn_lstm_v1.p -r /home/t-yuche/deep-video/data/frames/google_glass_lunch_with_restaurant_reporter_kevin_pang_DHkjf-znowA -t /home/t-yuche/neuraltalk/python_features/tool/tmp/google_glass_lunch_with_restaurant_reporter_kevin_pang_DHkjf-znowA_tasks.txt -f  /home/t-yuche/neuraltalk/python_features/caption/google_glass_lunch_with_restaurant_reporter_kevin_pang_DHkjf-znowA.pickle -of  /home/t-yuche/neuraltalk/python_features/caption/google_glass_lunch_with_restaurant_reporter_kevin_pang_DHkjf-znowA_5_caption.json &

python /home/t-yuche/neuraltalk/python_features/extract_features.py  --gpu --caffe ~/caffe/ --model_def /home/t-yuche/neuraltalk/python_features/deploy_features.prototxt --model /home/t-yuche/caffe/models/vgg_ilsvrc_16/VGG_ILSVRC_16_layers.caffemodel --files /home/t-yuche/neuraltalk/python_features/tool/tmp/christmas_break_gopro_CB662uFL8tY_tasks.txt --out /home/t-yuche/neuraltalk/python_features/caption/christmas_break_gopro_CB662uFL8tY.pickle
python /home/t-yuche/neuraltalk/predict_on_images.py /home/t-yuche/neuraltalk/models/flickr8k_cnn_lstm_v1.p -r /home/t-yuche/deep-video/data/frames/christmas_break_gopro_CB662uFL8tY -t /home/t-yuche/neuraltalk/python_features/tool/tmp/christmas_break_gopro_CB662uFL8tY_tasks.txt -f  /home/t-yuche/neuraltalk/python_features/caption/christmas_break_gopro_CB662uFL8tY.pickle -of  /home/t-yuche/neuraltalk/python_features/caption/christmas_break_gopro_CB662uFL8tY_5_caption.json &

python /home/t-yuche/neuraltalk/python_features/extract_features.py  --gpu --caffe ~/caffe/ --model_def /home/t-yuche/neuraltalk/python_features/deploy_features.prototxt --model /home/t-yuche/caffe/models/vgg_ilsvrc_16/VGG_ILSVRC_16_layers.caffemodel --files /home/t-yuche/neuraltalk/python_features/tool/tmp/meet_kumari_the_porcupine_ID5irdY08xA_tasks.txt --out /home/t-yuche/neuraltalk/python_features/caption/meet_kumari_the_porcupine_ID5irdY08xA.pickle
python /home/t-yuche/neuraltalk/predict_on_images.py /home/t-yuche/neuraltalk/models/flickr8k_cnn_lstm_v1.p -r /home/t-yuche/deep-video/data/frames/meet_kumari_the_porcupine_ID5irdY08xA -t /home/t-yuche/neuraltalk/python_features/tool/tmp/meet_kumari_the_porcupine_ID5irdY08xA_tasks.txt -f  /home/t-yuche/neuraltalk/python_features/caption/meet_kumari_the_porcupine_ID5irdY08xA.pickle -of  /home/t-yuche/neuraltalk/python_features/caption/meet_kumari_the_porcupine_ID5irdY08xA_5_caption.json &

python /home/t-yuche/neuraltalk/python_features/extract_features.py  --gpu --caffe ~/caffe/ --model_def /home/t-yuche/neuraltalk/python_features/deploy_features.prototxt --model /home/t-yuche/caffe/models/vgg_ilsvrc_16/VGG_ILSVRC_16_layers.caffemodel --files /home/t-yuche/neuraltalk/python_features/tool/tmp/red_suede_couch_prod_luke_ballistic_official_music_video__blake_graham_x_macale_media_CSbtEuoLj88_tasks.txt --out /home/t-yuche/neuraltalk/python_features/caption/red_suede_couch_prod_luke_ballistic_official_music_video__blake_graham_x_macale_media_CSbtEuoLj88.pickle
python /home/t-yuche/neuraltalk/predict_on_images.py /home/t-yuche/neuraltalk/models/flickr8k_cnn_lstm_v1.p -r /home/t-yuche/deep-video/data/frames/red_suede_couch_prod_luke_ballistic_official_music_video__blake_graham_x_macale_media_CSbtEuoLj88 -t /home/t-yuche/neuraltalk/python_features/tool/tmp/red_suede_couch_prod_luke_ballistic_official_music_video__blake_graham_x_macale_media_CSbtEuoLj88_tasks.txt -f  /home/t-yuche/neuraltalk/python_features/caption/red_suede_couch_prod_luke_ballistic_official_music_video__blake_graham_x_macale_media_CSbtEuoLj88.pickle -of  /home/t-yuche/neuraltalk/python_features/caption/red_suede_couch_prod_luke_ballistic_official_music_video__blake_graham_x_macale_media_CSbtEuoLj88_5_caption.json &


python /home/t-yuche/neuraltalk/python_features/extract_features.py  --gpu --caffe ~/caffe/ --model_def /home/t-yuche/neuraltalk/python_features/deploy_features.prototxt --model /home/t-yuche/caffe/models/vgg_ilsvrc_16/VGG_ILSVRC_16_layers.caffemodel --files /home/t-yuche/neuraltalk/python_features/tool/tmp/google_glass_films_google_glass__real_estate_tour_throughglass_7e5iDdPGeGA_tasks.txt --out /home/t-yuche/neuraltalk/python_features/caption/google_glass_films_google_glass__real_estate_tour_throughglass_7e5iDdPGeGA.pickle
python /home/t-yuche/neuraltalk/predict_on_images.py /home/t-yuche/neuraltalk/models/flickr8k_cnn_lstm_v1.p -r /home/t-yuche/deep-video/data/frames/google_glass_films_google_glass__real_estate_tour_throughglass_7e5iDdPGeGA -t /home/t-yuche/neuraltalk/python_features/tool/tmp/google_glass_films_google_glass__real_estate_tour_throughglass_7e5iDdPGeGA_tasks.txt -f  /home/t-yuche/neuraltalk/python_features/caption/google_glass_films_google_glass__real_estate_tour_throughglass_7e5iDdPGeGA.pickle -of  /home/t-yuche/neuraltalk/python_features/caption/google_glass_films_google_glass__real_estate_tour_throughglass_7e5iDdPGeGA_5_caption.json &

python /home/t-yuche/neuraltalk/python_features/extract_features.py  --gpu --caffe ~/caffe/ --model_def /home/t-yuche/neuraltalk/python_features/deploy_features.prototxt --model /home/t-yuche/caffe/models/vgg_ilsvrc_16/VGG_ILSVRC_16_layers.caffemodel --files /home/t-yuche/neuraltalk/python_features/tool/tmp/google_glass_elephants_EaShz4jRL_s_tasks.txt --out /home/t-yuche/neuraltalk/python_features/caption/google_glass_elephants_EaShz4jRL_s.pickle
python /home/t-yuche/neuraltalk/predict_on_images.py /home/t-yuche/neuraltalk/models/flickr8k_cnn_lstm_v1.p -r /home/t-yuche/deep-video/data/frames/google_glass_elephants_EaShz4jRL_s -t /home/t-yuche/neuraltalk/python_features/tool/tmp/google_glass_elephants_EaShz4jRL_s_tasks.txt -f  /home/t-yuche/neuraltalk/python_features/caption/google_glass_elephants_EaShz4jRL_s.pickle -of  /home/t-yuche/neuraltalk/python_features/caption/google_glass_elephants_EaShz4jRL_s_5_caption.json &

python /home/t-yuche/neuraltalk/python_features/extract_features.py  --gpu --caffe ~/caffe/ --model_def /home/t-yuche/neuraltalk/python_features/deploy_features.prototxt --model /home/t-yuche/caffe/models/vgg_ilsvrc_16/VGG_ILSVRC_16_layers.caffemodel --files /home/t-yuche/neuraltalk/python_features/tool/tmp/gopro_bali_christmas_holidays_20142015_zRw4EyYcvmA_tasks.txt --out /home/t-yuche/neuraltalk/python_features/caption/gopro_bali_christmas_holidays_20142015_zRw4EyYcvmA.pickle
python /home/t-yuche/neuraltalk/predict_on_images.py /home/t-yuche/neuraltalk/models/flickr8k_cnn_lstm_v1.p -r /home/t-yuche/deep-video/data/frames/gopro_bali_christmas_holidays_20142015_zRw4EyYcvmA -t /home/t-yuche/neuraltalk/python_features/tool/tmp/gopro_bali_christmas_holidays_20142015_zRw4EyYcvmA_tasks.txt -f  /home/t-yuche/neuraltalk/python_features/caption/gopro_bali_christmas_holidays_20142015_zRw4EyYcvmA.pickle -of  /home/t-yuche/neuraltalk/python_features/caption/gopro_bali_christmas_holidays_20142015_zRw4EyYcvmA_5_caption.json &


python /home/t-yuche/neuraltalk/python_features/extract_features.py  --gpu --caffe ~/caffe/ --model_def /home/t-yuche/neuraltalk/python_features/deploy_features.prototxt --model /home/t-yuche/caffe/models/vgg_ilsvrc_16/VGG_ILSVRC_16_layers.caffemodel --files /home/t-yuche/neuraltalk/python_features/tool/tmp/tcgs__sandwich_night_2013_through_google_glass_3njPQW34BFQ_tasks.txt --out /home/t-yuche/neuraltalk/python_features/caption/tcgs__sandwich_night_2013_through_google_glass_3njPQW34BFQ.pickle
python /home/t-yuche/neuraltalk/predict_on_images.py /home/t-yuche/neuraltalk/models/flickr8k_cnn_lstm_v1.p -r /home/t-yuche/deep-video/data/frames/tcgs__sandwich_night_2013_through_google_glass_3njPQW34BFQ -t /home/t-yuche/neuraltalk/python_features/tool/tmp/tcgs__sandwich_night_2013_through_google_glass_3njPQW34BFQ_tasks.txt -f  /home/t-yuche/neuraltalk/python_features/caption/tcgs__sandwich_night_2013_through_google_glass_3njPQW34BFQ.pickle -of  /home/t-yuche/neuraltalk/python_features/caption/tcgs__sandwich_night_2013_through_google_glass_3njPQW34BFQ_5_caption.json &


python /home/t-yuche/neuraltalk/python_features/extract_features.py  --gpu --caffe ~/caffe/ --model_def /home/t-yuche/neuraltalk/python_features/deploy_features.prototxt --model /home/t-yuche/caffe/models/vgg_ilsvrc_16/VGG_ILSVRC_16_layers.caffemodel --files /home/t-yuche/neuraltalk/python_features/tool/tmp/google_glass_on_planet_of_horses_L7wysTG37kk_tasks.txt --out /home/t-yuche/neuraltalk/python_features/caption/google_glass_on_planet_of_horses_L7wysTG37kk.pickle
python /home/t-yuche/neuraltalk/predict_on_images.py /home/t-yuche/neuraltalk/models/flickr8k_cnn_lstm_v1.p -r /home/t-yuche/deep-video/data/frames/google_glass_on_planet_of_horses_L7wysTG37kk -t /home/t-yuche/neuraltalk/python_features/tool/tmp/google_glass_on_planet_of_horses_L7wysTG37kk_tasks.txt -f  /home/t-yuche/neuraltalk/python_features/caption/google_glass_on_planet_of_horses_L7wysTG37kk.pickle -of  /home/t-yuche/neuraltalk/python_features/caption/google_glass_on_planet_of_horses_L7wysTG37kk_5_caption.json &



python /home/t-yuche/neuraltalk/python_features/extract_features.py  --gpu --caffe ~/caffe/ --model_def /home/t-yuche/neuraltalk/python_features/deploy_features.prototxt --model /home/t-yuche/caffe/models/vgg_ilsvrc_16/VGG_ILSVRC_16_layers.caffemodel --files /home/t-yuche/neuraltalk/python_features/tool/tmp/skating_with_google_glass_by_night_qK5gkJOvIvw_tasks.txt --out /home/t-yuche/neuraltalk/python_features/caption/skating_with_google_glass_by_night_qK5gkJOvIvw.pickle
python /home/t-yuche/neuraltalk/predict_on_images.py /home/t-yuche/neuraltalk/models/flickr8k_cnn_lstm_v1.p -r /home/t-yuche/deep-video/data/frames/skating_with_google_glass_by_night_qK5gkJOvIvw -t /home/t-yuche/neuraltalk/python_features/tool/tmp/skating_with_google_glass_by_night_qK5gkJOvIvw_tasks.txt -f  /home/t-yuche/neuraltalk/python_features/caption/skating_with_google_glass_by_night_qK5gkJOvIvw.pickle -of  /home/t-yuche/neuraltalk/python_features/caption/skating_with_google_glass_by_night_qK5gkJOvIvw_5_caption.json &

python /home/t-yuche/neuraltalk/python_features/extract_features.py  --gpu --caffe ~/caffe/ --model_def /home/t-yuche/neuraltalk/python_features/deploy_features.prototxt --model /home/t-yuche/caffe/models/vgg_ilsvrc_16/VGG_ILSVRC_16_layers.caffemodel --files /home/t-yuche/neuraltalk/python_features/tool/tmp/uts_boxing_for_mma_class_gopro_hero_3_HVtVpkkYGn0_tasks.txt --out /home/t-yuche/neuraltalk/python_features/caption/uts_boxing_for_mma_class_gopro_hero_3_HVtVpkkYGn0.pickle
python /home/t-yuche/neuraltalk/predict_on_images.py /home/t-yuche/neuraltalk/models/flickr8k_cnn_lstm_v1.p -r /home/t-yuche/deep-video/data/frames/uts_boxing_for_mma_class_gopro_hero_3_HVtVpkkYGn0 -t /home/t-yuche/neuraltalk/python_features/tool/tmp/uts_boxing_for_mma_class_gopro_hero_3_HVtVpkkYGn0_tasks.txt -f  /home/t-yuche/neuraltalk/python_features/caption/uts_boxing_for_mma_class_gopro_hero_3_HVtVpkkYGn0.pickle -of  /home/t-yuche/neuraltalk/python_features/caption/uts_boxing_for_mma_class_gopro_hero_3_HVtVpkkYGn0_5_caption.json &

python /home/t-yuche/neuraltalk/python_features/extract_features.py  --gpu --caffe ~/caffe/ --model_def /home/t-yuche/neuraltalk/python_features/deploy_features.prototxt --model /home/t-yuche/caffe/models/vgg_ilsvrc_16/VGG_ILSVRC_16_layers.caffemodel --files /home/t-yuche/neuraltalk/python_features/tool/tmp/homespace_red_sofaliving_room_inspiration_VDbvAxmM1VM_tasks.txt --out /home/t-yuche/neuraltalk/python_features/caption/homespace_red_sofaliving_room_inspiration_VDbvAxmM1VM.pickle
python /home/t-yuche/neuraltalk/predict_on_images.py /home/t-yuche/neuraltalk/models/flickr8k_cnn_lstm_v1.p -r /home/t-yuche/deep-video/data/frames/homespace_red_sofaliving_room_inspiration_VDbvAxmM1VM -t /home/t-yuche/neuraltalk/python_features/tool/tmp/homespace_red_sofaliving_room_inspiration_VDbvAxmM1VM_tasks.txt -f  /home/t-yuche/neuraltalk/python_features/caption/homespace_red_sofaliving_room_inspiration_VDbvAxmM1VM.pickle -of  /home/t-yuche/neuraltalk/python_features/caption/homespace_red_sofaliving_room_inspiration_VDbvAxmM1VM_5_caption.json &


python /home/t-yuche/neuraltalk/python_features/extract_features.py  --gpu --caffe ~/caffe/ --model_def /home/t-yuche/neuraltalk/python_features/deploy_features.prototxt --model /home/t-yuche/caffe/models/vgg_ilsvrc_16/VGG_ILSVRC_16_layers.caffemodel --files /home/t-yuche/neuraltalk/python_features/tool/tmp/red_couch_interviews_2015_totalsports_xterra_grabouw_U0u-NCw78ik_tasks.txt --out /home/t-yuche/neuraltalk/python_features/caption/red_couch_interviews_2015_totalsports_xterra_grabouw_U0u-NCw78ik.pickle
python /home/t-yuche/neuraltalk/predict_on_images.py /home/t-yuche/neuraltalk/models/flickr8k_cnn_lstm_v1.p -r /home/t-yuche/deep-video/data/frames/red_couch_interviews_2015_totalsports_xterra_grabouw_U0u-NCw78ik -t /home/t-yuche/neuraltalk/python_features/tool/tmp/red_couch_interviews_2015_totalsports_xterra_grabouw_U0u-NCw78ik_tasks.txt -f  /home/t-yuche/neuraltalk/python_features/caption/red_couch_interviews_2015_totalsports_xterra_grabouw_U0u-NCw78ik.pickle -of  /home/t-yuche/neuraltalk/python_features/caption/red_couch_interviews_2015_totalsports_xterra_grabouw_U0u-NCw78ik_5_caption.json &

python /home/t-yuche/neuraltalk/python_features/extract_features.py  --gpu --caffe ~/caffe/ --model_def /home/t-yuche/neuraltalk/python_features/deploy_features.prototxt --model /home/t-yuche/caffe/models/vgg_ilsvrc_16/VGG_ILSVRC_16_layers.caffemodel --files /home/t-yuche/neuraltalk/python_features/tool/tmp/zebra_outside_the_tent_n6C0gU2kS9Y_tasks.txt --out /home/t-yuche/neuraltalk/python_features/caption/zebra_outside_the_tent_n6C0gU2kS9Y.pickle
python /home/t-yuche/neuraltalk/predict_on_images.py /home/t-yuche/neuraltalk/models/flickr8k_cnn_lstm_v1.p -r /home/t-yuche/deep-video/data/frames/zebra_outside_the_tent_n6C0gU2kS9Y -t /home/t-yuche/neuraltalk/python_features/tool/tmp/zebra_outside_the_tent_n6C0gU2kS9Y_tasks.txt -f  /home/t-yuche/neuraltalk/python_features/caption/zebra_outside_the_tent_n6C0gU2kS9Y.pickle -of  /home/t-yuche/neuraltalk/python_features/caption/zebra_outside_the_tent_n6C0gU2kS9Y_5_caption.json &


python /home/t-yuche/neuraltalk/python_features/extract_features.py  --gpu --caffe ~/caffe/ --model_def /home/t-yuche/neuraltalk/python_features/deploy_features.prototxt --model /home/t-yuche/caffe/models/vgg_ilsvrc_16/VGG_ILSVRC_16_layers.caffemodel --files /home/t-yuche/neuraltalk/python_features/tool/tmp/christmas_announcement_another_one_in_the_oven__google_glass_zfABTFNWcYU_tasks.txt --out /home/t-yuche/neuraltalk/python_features/caption/christmas_announcement_another_one_in_the_oven__google_glass_zfABTFNWcYU.pickle
python /home/t-yuche/neuraltalk/predict_on_images.py /home/t-yuche/neuraltalk/models/flickr8k_cnn_lstm_v1.p -r /home/t-yuche/deep-video/data/frames/christmas_announcement_another_one_in_the_oven__google_glass_zfABTFNWcYU -t /home/t-yuche/neuraltalk/python_features/tool/tmp/christmas_announcement_another_one_in_the_oven__google_glass_zfABTFNWcYU_tasks.txt -f  /home/t-yuche/neuraltalk/python_features/caption/christmas_announcement_another_one_in_the_oven__google_glass_zfABTFNWcYU.pickle -of  /home/t-yuche/neuraltalk/python_features/caption/christmas_announcement_another_one_in_the_oven__google_glass_zfABTFNWcYU_5_caption.json &

