
python /home/t-yuche/neuraltalk/python_features/vgg_classify.py --gpu --caffe ~/caffe/ --model_def /home/t-yuche/neuraltalk/python_features/VGG_ILSVRC_16_layers_deploy.prototxt --model /home/t-yuche/caffe/models/vgg_ilsvrc_16/VGG_ILSVRC_16_layers.caffemodel --files /home/t-yuche/neuraltalk/python_features/tool/tmp/tcgs__sandwich_night_2013_through_google_glass_3njPQW34BFQ_tasks.txt --output_file /home/t-yuche/neuraltalk/python_features/recognition/tcgs__sandwich_night_2013_through_google_glass_3njPQW34BFQ_recog.json

python /home/t-yuche/neuraltalk/python_features/vgg_classify.py --gpu --caffe ~/caffe/ --model_def /home/t-yuche/neuraltalk/python_features/VGG_ILSVRC_16_layers_deploy.prototxt --model /home/t-yuche/caffe/models/vgg_ilsvrc_16/VGG_ILSVRC_16_layers.caffemodel --files /home/t-yuche/neuraltalk/python_features/tool/tmp/google_glass_on_planet_of_horses_L7wysTG37kk_tasks.txt --output_file /home/t-yuche/neuraltalk/python_features/recognition/google_glass_on_planet_of_horses_L7wysTG37kk_recog.json


python /home/t-yuche/neuraltalk/python_features/vgg_classify.py --gpu --caffe ~/caffe/ --model_def /home/t-yuche/neuraltalk/python_features/VGG_ILSVRC_16_layers_deploy.prototxt --model /home/t-yuche/caffe/models/vgg_ilsvrc_16/VGG_ILSVRC_16_layers.caffemodel --files /home/t-yuche/neuraltalk/python_features/tool/tmp/skating_with_google_glass_by_night_qK5gkJOvIvw_tasks.txt --output_file /home/t-yuche/neuraltalk/python_features/recognition/skating_with_google_glass_by_night_qK5gkJOvIvw_recog.json

python /home/t-yuche/neuraltalk/python_features/vgg_classify.py --gpu --caffe ~/caffe/ --model_def /home/t-yuche/neuraltalk/python_features/VGG_ILSVRC_16_layers_deploy.prototxt --model /home/t-yuche/caffe/models/vgg_ilsvrc_16/VGG_ILSVRC_16_layers.caffemodel --files /home/t-yuche/neuraltalk/python_features/tool/tmp/uts_boxing_for_mma_class_gopro_hero_3_HVtVpkkYGn0_tasks.txt --output_file /home/t-yuche/neuraltalk/python_features/recognition/uts_boxing_for_mma_class_gopro_hero_3_HVtVpkkYGn0_recog.json

python /home/t-yuche/neuraltalk/python_features/vgg_classify.py --gpu --caffe ~/caffe/ --model_def /home/t-yuche/neuraltalk/python_features/VGG_ILSVRC_16_layers_deploy.prototxt --model /home/t-yuche/caffe/models/vgg_ilsvrc_16/VGG_ILSVRC_16_layers.caffemodel --files /home/t-yuche/neuraltalk/python_features/tool/tmp/homespace_red_sofaliving_room_inspiration_VDbvAxmM1VM_tasks.txt --output_file /home/t-yuche/neuraltalk/python_features/recognition/homespace_red_sofaliving_room_inspiration_VDbvAxmM1VM_recog.json

python /home/t-yuche/neuraltalk/python_features/vgg_classify.py --gpu --caffe ~/caffe/ --model_def /home/t-yuche/neuraltalk/python_features/VGG_ILSVRC_16_layers_deploy.prototxt --model /home/t-yuche/caffe/models/vgg_ilsvrc_16/VGG_ILSVRC_16_layers.caffemodel --files /home/t-yuche/neuraltalk/python_features/tool/tmp/red_couch_interviews_2015_totalsports_xterra_grabouw_U0u-NCw78ik_tasks.txt --output_file /home/t-yuche/neuraltalk/python_features/recognition/red_couch_interviews_2015_totalsports_xterra_grabouw_U0u-NCw78ik_recog.json

python /home/t-yuche/neuraltalk/python_features/vgg_classify.py --gpu --caffe ~/caffe/ --model_def /home/t-yuche/neuraltalk/python_features/VGG_ILSVRC_16_layers_deploy.prototxt --model /home/t-yuche/caffe/models/vgg_ilsvrc_16/VGG_ILSVRC_16_layers.caffemodel --files /home/t-yuche/neuraltalk/python_features/tool/tmp/zebra_outside_the_tent_n6C0gU2kS9Y_tasks.txt --output_file /home/t-yuche/neuraltalk/python_features/recognition/zebra_outside_the_tent_n6C0gU2kS9Y_recog.json


python /home/t-yuche/neuraltalk/python_features/vgg_classify.py --gpu --caffe ~/caffe/ --model_def /home/t-yuche/neuraltalk/python_features/VGG_ILSVRC_16_layers_deploy.prototxt --model /home/t-yuche/caffe/models/vgg_ilsvrc_16/VGG_ILSVRC_16_layers.caffemodel --files /home/t-yuche/neuraltalk/python_features/tool/tmp/christmas_announcement_another_one_in_the_oven__google_glass_zfABTFNWcYU_tasks.txt --output_file /home/t-yuche/neuraltalk/python_features/recognition/christmas_announcement_another_one_in_the_oven__google_glass_zfABTFNWcYU_recog.json

